### ISSUE TITLE
No CPL file

### ISSUE THREAD

**Issue by malloy139** [TrimVa/ZeeFlora#1]
Could you please provide the CPL file so one could order assembled PCBs from JLCPCB?

**Comment by TrimVa** [comment]
no sorry, I sell assembled pcb
--
vendredi, 10 septembre 2021, 10:08PM +02:00 de malloy139  ***@***.*** :

**Comment by malloy139** [comment]
Could you then please provide a link to your shop?

**Comment by TrimVa** [comment]
so, for the moment my online store is not operational, I sell my products via telegram :) I have created a group where I regularly send photos / videos of materials that I sell, on the other hand I am French and  sells only in Europe
https://t.me/tech4you_shop
--
Envoyé depuis l'application myMail pour Android vendredi, 10 septembre 2021, 10:16PM +02:00 de malloy139  ***@***.*** :
